version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/backend
      - ./backend/data/web/static:/data/web/static/
      - ./backend/data/web/media:/data/web/media/
    ports:
      - "8000:8000"
    env_file:
      - ./backend/dotenv_files/.env
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend

  db:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./backend/data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./backend/dotenv_files/.env
